name: univ_adventure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^7.0.3
  qrscan: ^0.3.3
  permission_handler: ^11.3.1
  flutter_svg: ^0.22.0
  optional: ^6.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/POI.json
    - assets/quests.json
    - assets/images/backgroundProfile.png
    - assets/news.json
